export const BRAND = {
  name: 'HushPic',
  domain: 'HushPic.com',
  url: 'https://HushPic.com',
  fileType: 'IMAGE',
  operator: 'Creignificent LLC',
  sponsorLine: 'Sponsored by CREIGNIFICENT LLC.',
  job: 'Resize, compress and convert your images locally in your browser.',
  oneLiner: 'HushPic — image tools that process files locally in your browser. Image bytes are not uploaded by HushPic for processing. 3 free uses/day. Pro for unlimited.',
  privacyLine: 'Image bytes stay on your device during processing. Account, billing, and usage metadata may sync securely.',
  supportEmail: 'CreigTerrence@gmail.com',
  freeQuotaLimit: 3,
  freeMaxFileSizeMB: 25,
  proMaxFileSizeMB: 500,
  proPriceMonthly: 9,
} as const;
